services:
  - type: web
    name: cat-oracle
    env: python
    buildCommand: curl -sL https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz -o ffmpeg.tar.xz && tar -xf ffmpeg.tar.xz && mv ffmpeg-*/ffmpeg ./ && chmod +x ffmpeg && ls -la ffmpeg && pip install -r requirements.txt
    startCommand: python english_bot/bot_bilingual.py
    runtime: python
    pythonVersion: 3.12.0
    envVars:
      - key: 8827616686:AAFwdGgz5dkKEe_VbXvfHHecZk3Se0oOPek
        sync: false
      - key: 316151942
        sync: false


